directory: ~/code/beets/library
library: ~/code/beets/library/library.db

threaded: no
original_year: yes

paths:
    default: $albumartist/%if{$original_year,$original_year,$year} - $album%aunique{}/$track $title
    singleton: $artist/singles/%if{$original_year,$original_year,$year} - $title
    comp: compilations/%if{$original_year,$original_year,$year} - $albumartist - $album%aunique{}/$track $artist - $title

pluginpath:
    - ~/code/beets/beets-copyartifacts/build/lib/beetsplug
    - ~/code/beets/beets-setlister/beetsplug
    - ~/code/beets/beets-link/beetsplug

plugins: discogs missing embedart info types duplicates edit fromfilename copyartifacts link setlister

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>"\*\|\\]': '_'
    ':': '-'
    '\?': '_'
    '\.$': '.'
    '\s+$': ''
    '^\s+': ''
    '^-': '_'

aunique:
    keys: albumartist album
    disambiguators: albumdisambig country albumtype year label catalognum releasegroupdisambig
    bracket: '()'

setlister:
    playlist_dir: ~/code/beets/library
    api_key: UdgWf-HnBCKdFfmpJnA7OgxaxVhPOmbC0Qi9